// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4j-WaEjp6rVZXMXt3QfL3EfEK7rvq4lI',
    appId: '1:152149271375:web:82dc817fd3c1a1e2c01b3a',
    messagingSenderId: '152149271375',
    projectId: 'my-tool-shed-8565f',
    authDomain: 'my-tool-shed-8565f.firebaseapp.com',
    storageBucket: 'my-tool-shed-8565f.firebasestorage.app',
    measurementId: 'G-9HSWSPKBRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7D1WfiGdxrcprt45sj2uo_GSfceaZbU',
    appId: '1:152149271375:android:afc4125c50607777c01b3a',
    messagingSenderId: '152149271375',
    projectId: 'my-tool-shed-8565f',
    storageBucket: 'my-tool-shed-8565f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6SLeKmVHm9fj9zU9mc5JooIRKy1i7TUk',
    appId: '1:152149271375:ios:eb6f5235f71eee72c01b3a',
    messagingSenderId: '152149271375',
    projectId: 'my-tool-shed-8565f',
    storageBucket: 'my-tool-shed-8565f.firebasestorage.app',
    iosBundleId: 'com.example.myToolShed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6SLeKmVHm9fj9zU9mc5JooIRKy1i7TUk',
    appId: '1:152149271375:ios:eb6f5235f71eee72c01b3a',
    messagingSenderId: '152149271375',
    projectId: 'my-tool-shed-8565f',
    storageBucket: 'my-tool-shed-8565f.firebasestorage.app',
    iosBundleId: 'com.example.myToolShed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4j-WaEjp6rVZXMXt3QfL3EfEK7rvq4lI',
    appId: '1:152149271375:web:1374fe363ddd3cacc01b3a',
    messagingSenderId: '152149271375',
    projectId: 'my-tool-shed-8565f',
    authDomain: 'my-tool-shed-8565f.firebaseapp.com',
    storageBucket: 'my-tool-shed-8565f.firebasestorage.app',
    measurementId: 'G-K1VXSL444J',
  );
}
